name = "DocumenterTools"
uuid = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"

[compat]
DocStringExtensions = ">= 0.2"

[extras]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Example", "Pkg", "Test"]
